import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from Cualca" });
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Mini Chat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Mini Chat</span>
          </h1>

          <div className="flex flex-col items-center gap-3">
            {!sessionData && (
              <p className="text-3xl text-white">
                ¿Que esperas para chatear con gente de cualquier lado?
              </p>
            )}
            <SignInButton />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const SignInButton: React.FC = () => {
  const { data: sessionData } = useSession();
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign Out" : "Sign In"}
      </button>
    </div>
  );
};
