import { type NextPage } from "next";
import Head from "next/head";

import Chat from "../components/Chat";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mini Chat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-[calc(100vh - 1000px)] flex flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center px-4 py-10 ">
          <Chat />
        </div>
      </main>
    </>
  );
};

export default Home;
